# As of 2021, preserving comments in yaml updating is still not supported with PyYAML.
# Consider pyckage ruamel.yaml which is a derivative of PyYAML and supports round trip
# preservation of comments.
# Section: general
general:
    log_type: cm        # Sub-folder of log platform must be consistent with name here
    log_head: 24        # Log head offset. Default value is from standard timestamp
    training: true      # true for training, and false for prediction
    metrics: false
    context: TEMPUPDT   # One of TEMPUPDT, LOGLAB, OLDSCHOOL, DEEPLOG AND LOGLIZER
    intmdt: true        # Save intermediate results to files
    aim: true           # Process data always in memory, otherwise intmdt must be true

# Section: templte
template:
    size: 2000          # The max size of template library

# Section: loglab
loglab:
    model: RFC          # Classical machine learning models
    window_size: 10     # 1/2 window around the axis, unit is log

# Section: deeplog
deeplog:
    model: EXEC         # Execution path model. Parameter model PARAM is not implemented
    window_size: 15     # Sequence length, unit is log
    batch_size: 32
    num_epochs: 150
    num_workers: 0
    hidden_size: 128    # Hidden size of LSTM
    topk: 10
    device: cpu
    num_dir: 1          # Number of directions of LSTM

# Section: loglizer
loglizer:
    model: DT           # Classical machine learning models
    window_size: 10000  # Time window size, unit is ms
    window_step: 5000   # Sliding window step, unit is ms
